[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.65.3"
  NODE_VERSION = "11.4.0"
  YARN_VERSION = "1.17.3"
  HUGO_ENV = "staging"

[context.production]
  command = "./scripts/build -b ${URL}/"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "./scripts/build -b ${DEPLOY_PRIME_URL}/"

[context.branch-deploy]
  command = "./scripts/build -b ${DEPLOY_PRIME_URL}/"
