#!/usr/bin/env ruby

require 'json'
require 'open-uri'
require 'ostruct'
require 'psych'

providers = JSON.parse open("http://localhost:1337/providers?_limit=1000000").read

channels = JSON.parse open("http://localhost:1337/channels?_limit=1000000").read

class Hash
  def to_ostruct
    JSON.parse to_json, object_class: OpenStruct
  end
end

i = 0
channels.each do |result|
  i = i + 1
  channel = result.to_ostruct
  channel_path = "channels/#{ channel.slug }"
  channel_folder = "content/#{ channel_path }/"

  puts "\n\n#{i} #{ channel.name }"
  puts "#{ channel_folder }"

  `rm -rf #{ channel_folder }`
  `hugo new --kind channel "#{ channel_path }"`

    channel_page = "#{ channel_folder }_index.md"

  File.open(channel_page, 'r+') do |file|
    file.seek(-4, IO::SEEK_END)
    file.puts("title: |\n  #{ channel.name }")
    file.puts("slug: #{ channel.slug }")
    file.puts("url: /#{ channel.slug }/")
    file.puts("date: #{ channel.created_at }")
    file.puts("description: |\n  #{ channel.description }")
    file.puts("image: #{ channel&.image&.url }")
    file.puts("---")
  end

  channel.contents.each do |content|
    content_slug = content.slug
    content_path = "#{ channel_path }/#{ content_slug }"
    content_folder = "content/#{ content_path }/"

    `hugo new --kind content "#{ content_path }"`

    content_page = "#{ content_folder }_index.md"

    File.open(content_page, 'r+') do |file|
      file.seek(-4, IO::SEEK_END)
      file.puts("title: |\n  #{ content.name }")
      file.puts("slug: #{ content.slug }")
      file.puts("url: /#{ channel.slug }/#{ content.slug }/")
      file.puts("date: #{ channel.published_at }")
      file.puts("description: |\n  #{ content.description }")
      file.puts("image: #{ content.image.url }")

      file.puts("sources:")
      content.sources.each do |source|
        provider = providers.find { |p| p['name'] == source.provider.name }
        url = provider['urls'].find { |p| p['type'] == "content" }
        file.puts("  #{ source.provider.name}: #{ url['pattern'].gsub('{{slug}}', source.slug) }")
      end
      file.puts("---")
    end
  end
end
